/**
 * The `flarum_dev` tool: a development reference for building and reviewing
 * Flarum 2.0 extensions, served to the AI agent a developer is working with
 * through this MCP.
 *
 * Unlike flarum_docs_* (which proxies the official docs live), this is curated
 * guidance: the conventions the official docs establish, the de-facto
 * FriendsOfFlarum standard, and patterns that prevent the bugs that actually
 * bite in production. It is intentionally general (no vendor-specific
 * branding/naming) so it applies to any Flarum 2.0 extension.
 *
 * Content is static, so this tool needs no forum connection or API key and is
 * safe in read-only mode.
 */

import { z } from "zod";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";

const TITLE = "Flarum 2.0 extension development reference";

const INTRO =
  "A development reference for building and reviewing a Flarum 2.0 extension. It covers the " +
  "conventions the official docs establish, the de-facto FriendsOfFlarum standard, and patterns " +
  "that prevent real production bugs. Use `flarum_docs_search`/`flarum_docs_get` for the authoritative " +
  "API reference; use this for the conventions and judgement the docs don't spell out. " +
  "Pass a `topic` to narrow to one section.";

const SECTIONS: Record<string, { title: string; body: string }> = {
  scaffold: {
    title: "Scaffold & architecture",
    body: `- **Extenders only.** Everything an extension does goes through declarative \`Extend\\*\` extenders (PHP) and the JS \`extend()\`/\`override()\` API. This is the compatibility guarantee: staying inside extenders is what lets a future Flarum minor not break you. Never edit core or another extension's internals to get an effect.
- **Three layers**: backend (OO PHP + Laravel components, dependency injection), the JSON:API public API, and the Mithril.js frontend SPA. A feature often touches all three (DB structure → API field → frontend display).
- **Standard layout**: \`extend.php\` (the extender list), \`src/\` (PHP, PSR-4), \`js/src/\` (TS/ESM source) with \`js/dist/\` committed, \`less/\`, \`locale/en.yml\`, \`migrations/\`, \`tests/\`, \`.github/workflows/\`, \`phpstan.neon\`, \`composer.json\`, \`README.md\`, \`LICENSE\`.
- **Use \`flarum-cli\`** to scaffold and to add/maintain infra: \`flarum-cli init\`, then \`flarum-cli infra backendTesting | frontendTesting | phpstan | githubActions\`. It keeps you aligned with the current conventions; record what it manages in \`extra.flarum-cli.modules\`.
- **Drop the \`autoload\` block entirely** for a JS-only extension (no \`src/\` PHP) instead of leaving a PSR-4 mapping pointing at a non-existent directory.
- **Community-health files** for anything published: \`.github/ISSUE_TEMPLATE\`, \`PULL_REQUEST_TEMPLATE.md\`, \`SECURITY.md\`, \`FUNDING.yml\`. If you maintain several extensions, a shared \`<org>/.github\` repo lets them all inherit one set instead of copying per-repo. Credit the upstream in the README when porting a 1.x extension.`,
  },
  composer: {
    title: "composer.json",
    body: `- \`type\` MUST be \`flarum-extension\`; \`require\` \`flarum/core: ^2.0\` and an explicit \`php\` constraint (keep it in sync with the README).
- **No \`version\` field**, version comes from git tags (Packagist reads tags).
- \`extra.flarum-extension\`: \`title\`, \`category\`, \`icon\`; \`optional-dependencies\` (array of extension IDs your code soft-integrates with) and also list those in \`require-dev\` so tests can enable them. Declare \`migrations: migrations\` when present.
- \`require-dev\`: \`flarum/testing: ^2.0\` and \`flarum/phpstan: ^2.0\` (+ any optional-dep packages exercised in tests).
- \`scripts\` + \`scripts-descriptions\`: \`test\` (→ \`test:unit\` + \`test:integration\`), \`test:unit\`, \`test:integration\`, \`test:setup\`, \`analyse:phpstan\`, \`clear-cache:phpstan\`.
- \`autoload-dev\` PSR-4 maps \`<Vendor>\\<Ext>\\Tests\\\` → \`tests/\`.
- While Flarum 2.0 is pre-stable, add \`"minimum-stability": "beta"\` (or \`dev\`) + \`"prefer-stable": true\` so dev deps resolve.
- **Porting a 1.x extension?** Add \`"replace": { "<old/package>": "*" }\` so the original package name resolves to your fork, and credit the original in the README.`,
  },
  frontend: {
    title: "Frontend (TypeScript / Mithril)",
    body: `- **TypeScript + ESM** under \`js/src/\`, with \`js/forum.js\`/\`js/admin.js\` as one-line re-export shims. Toolchain: \`flarum-webpack-config ^3\`, \`flarum-tsconfig ^2\`, \`typescript ^5\`, webpack 5.
- **Commit \`js/dist/\`** (so installs need no build step); gitignore \`node_modules\`, \`dist-typings\`, \`dist/*.map\`. The build transpiles via babel/preset-typescript (not tsc), so pure type-only edits leave \`dist\` byte-identical, verify that when bumping TS.
- **Lazy-chunk-safe extends**: extend components by **string path** (\`extend('flarum/forum/components/CommentPost', 'headerItems', ...)\`) with a type-only \`import type\`, not a runtime \`import\` of the component, a runtime import forces the component (and its chunk) eager and breaks code-splitting.
- **Read boot data in initializers from \`app.data\`/the payload**, not \`app.forum\`, \`app.forum\` isn't built yet when initializers run.
- **Resolve translations at render time**, never at module load (a top-level \`app.translator.trans(...)\` freezes to the English fallback).
- **Integrating with another extension's component** (e.g. FoF widgets): resolve its base classes at initializer time via the registry (\`flarum.reg.get('ext-id', ...)\`), not a top-level \`ext:\` import, to avoid load-order crashes.
- **Sanitize before \`m.trust()\`**: run any user/admin-supplied HTML through DOMPurify; prefer \`textContent\` over \`innerHTML\`; scope theme CSS classes so states don't bleed; make aria-labels translatable.
- **Prefer render-driven processing** (component \`oncreate\`/\`onupdate\`) over \`setInterval\` DOM polling.
- **\`autoExportLoader\` mangles exported names that contain digits** (a top-level \`export const pad2 = …\` can be re-exported as \`twoDigits\`/something unexpected). A single bad export doesn't just break your bundle, it can break *other* extensions' bundles loaded after yours. Avoid digits in exported identifier names, and verify the built bundle actually exports what you expect.
- **Non-discussion notifications group under the forum title** ("Flarum") by default. If your extension emits notifications that aren't about a discussion, override \`NotificationList\` content to relabel them per-extension, or they'll all bucket together confusingly.
- **Honor the reading-size / UI-scale contract so you're compatible with text-resize controls on day one.** Forums that let users adjust text size expose it as CSS custom properties on \`<html>\`: \`--lr-text-scale\` for reading text and \`--lr-ui-scale\` for chrome (both default \`1\`, applied only while the \`lr-text-scaling\`/\`lr-ui-scaling\` gate classes are present, this is the Font Sizer extension's contract). Opt your content in two equivalent ways, **both no-ops when no such control is installed** (the var falls back to \`1\`): (1) add the plain class \`FontSizer-text\` to body-sized readable content (or \`FontSizer-ui\` to chrome), the control ships \`font-size: calc(1em * var(--lr-text-scale, 1)) !important\` for it, and it's a plain class so it needs no import; or (2) in your own LESS, wrap each font-size you control: \`font-size: calc(<size> * var(--lr-text-scale, 1))\`. Pick (2) for anything sized in \`rem\`/\`px\`.
- **Reading-scale gotcha, \`1em\` is the *inherited* (parent) size, not the element's own.** So the \`FontSizer-text\` class (\`calc(1em * var)\`) is only correct for body-sized text where the element's size ≈ its parent's. On a big \`rem\`/\`px\` heading or hero, \`1em * scale\` can resolve *smaller* than the heading and **shrink** it, never put \`FontSizer-text\` on a heading. Instead multiply the element's own size: \`font-size: calc(1.8rem * var(--lr-text-scale, 1))\`. Verify by setting \`--lr-text-scale\` (e.g. to \`1.3\`) and confirming the computed \`font-size\` actually grew.`,
  },
  backend: {
    title: "Backend (API resources, models, migrations)",
    body: `- **Fail-closed serializer/resource fields**: any per-request boolean shipped on a broadly-fetched resource (e.g. \`ForumResource\` fields on every forum response) should wrap \`can()\`/attribute reads in try/catch and degrade to \`false\`, a throwing field must not 500 the whole boot payload. Don't \`resolve()\` services inside a field closure; inject via the resource constructor.
- **Adding a field/relationship to an existing resource** (core's \`UserResource\`/\`DiscussionResource\`/\`PostResource\`, or another extension's): use \`Extend\\ApiResource(TargetResource::class)->fields(MyFields::class)\`, where \`MyFields\` is an invokable, container-resolved class returning \`Schema\\*\` objects (\`Schema\\Boolean::make('canX')\`, \`Schema\\Str\`, \`Schema\\Relationship\\ToOne\`/\`ToMany\`). Read with \`->get(fn ($model, $context) => …)\`; make writable with \`->writable(fn ($model, $context) => $context->getActor()->can(...))\` plus \`->set(...)\` (permission gate on \`writable\`, the mutation in \`set\`); hide output with \`->visible(false)\` or a closure. **Fail closed**: a per-row \`->get()\`/\`->visible()\` that reads \`can()\`/state must try/catch to a safe default, because a throw there 500s the whole collection (every row of an index, or the \`forum\` object on every page). Inject services into the fields-class constructor, never \`resolve()\`/\`app()\` inside the closure. Avoid N+1: eager-load via the relationship \`->scope()\` / endpoint default-includes, and use \`Schema\\Integer::make(...)->countRelation('x')\` for counts, not a per-row \`count()\`. Adding to \`ForumResource\` (loads on every page, has no backing model so every field needs \`->get()\`): keep getters O(1) with no per-request queries. To target another extension's resource, wrap the \`ApiResource\` in \`Extend\\Conditional()->whenExtensionEnabled('<ext-id>', ...)\`.
- **Adding a notification type**: register \`Extend\\Notification()->type(MyBlueprint::class, ['alert', 'email'])\` (the second arg is the channels pre-checked in the user's preference grid; 2.0 has no serializer arg). The Blueprint implements \`BlueprintInterface\` (\`getFromUser\`/\`getSubject\`/\`getData\` + static \`getType\`/\`getSubjectModel\`), plus the marker \`AlertableInterface\` for the alert channel and \`MailableInterface\` (with an \`Extend\\View\` namespace + blade templates) for email; a channel's preference only exists if its interface is implemented. **Send** by injecting \`Flarum\\Notification\\NotificationSyncer\` and calling \`->sync(new MyBlueprint(...), $recipients)\`: it honors each user's per-channel preference for you (don't check it yourself), and re-syncing with a smaller recipient list retracts the alert. Frontend: register the alert component with \`Extend.Notification().add('myType', MyComponent)\` and add a \`NotificationGrid\` \`notificationTypes\` row (keys must equal the \`getType()\` string). Gotchas: never notify the actor (\`getFromUser\`); resolve recipients inside a queued job and chunk the query; store any link data you need in \`getData()\` since the subject may be deleted before send; a notification whose subject isn't a \`Discussion\` (and has no \`discussion()\` relation) groups under the forum title unless you override \`NotificationList\` content.
- **Make content filterable/searchable.** There is no \`Extend\\Filter\` in 2.0; filters, searchers, and full-text all register through \`Extend\\SearchDriver(DatabaseSearchDriver::class)\`. The common case is a **filter** on an existing resource: write a class implementing \`Flarum\\Search\\Filter\\FilterInterface\` (\`getFilterKey()\` returns the public \`filter[key]\` param; \`filter(SearchState $state, $value, bool $negate): void\` constrains \`$state->getQuery()\`, which is already visibility-scoped), validate input with \`ValidateFilterTrait\` (\`asString\`/\`asInt\`/...), honor \`$negate\`, and register via \`->addFilter(DiscussionSearcher::class, MyFilter::class)\`. Gambits (the \`tag:foo\` search-bar shorthand) are **frontend-only** now (\`Extend.Search().gambit(...)\`) and just emit a \`filter[...]\`. A brand-new searchable resource needs \`->addSearcher(Model::class, MySearcher::class)\` (its searcher returns a \`whereVisibleTo($actor)\` query) plus \`->setFulltext(...)\`. Gotchas: a filter that joins other tables must visibility-scope those too (never widen beyond what the actor sees); \`filter[x]\` is stable public API; keep constraints set-based (a subselect), not per-row.
- **URL-addressable model (slug).** Register with \`Extend\\ModelUrl(MyModel::class)->addSlugDriver('default', MyDriver::class)\` (a \`'default'\` key is required); the admin picks the active driver via a \`slug_driver_<FQCN>\` setting. The driver implements \`Flarum\\Http\\SlugDriverInterface\`: \`toSlug($model): string\` and \`fromSlug(string, User $actor): AbstractModel\`, where \`fromSlug\` MUST resolve through an actor-scoped repository so a slug for a hidden model 404s (never \`Model::find()\` raw). Resolve/generate in PHP via \`Flarum\\Http\\SlugManager->forResource(Model::class)->fromSlug()/toSlug()\`; expose a \`slug\` attribute on the resource and honor \`?bySlug=true\` in \`find()\`. Frontend: \`Extend.Routes().add('name', '/x/:slug', Page).helper('name', m => app.route('name', { slug: m.slug() }))\`. Robust pattern: an \`<id>-<title>\` slug so a changed title still resolves and the id stays canonical (id-prefixed slugs are collision-free); pure-attribute slugs must be unique and break old URLs on rename.
- **Custom post formatting (s9e TextFormatter)** via \`Extend\\Formatter\`: \`->configure(fn ($config) => …)\` runs at **compile time and is cached**, so register tags/BBCode/attributes there but **never per-user, per-request, or permission data** (a config change needs \`cache:clear\`). Per-context substitution goes in the runtime hooks \`->parse\`/\`->render\`/\`->unparse\` (each must **return** the text/xml; inject runtime values with \`->addParameterByName('actor')\`). Security: don't inject raw HTML; define an s9e tag with an XSL \`template\` and pass dynamic values as **attributes**, which s9e escapes.
- **No side effects on GET / serialization**: never do a write while serializing a read. Move state-changing work to an explicit POST route.
- **Gate every endpoint explicitly**: \`assertCan\`/\`assertRegistered\`/\`assertAdmin\` in endpoint authorization, and define abilities via \`Access\\Policy\` rather than ad-hoc checks. On a private forum, scope list/index queries behind the \`viewForum\` permission so a guest can't enumerate rows. Default to deny; make a new capability opt-in via a seeded permission, not implicitly available.
- **Structured error handling** (\`Extend\\ErrorHandling\`): for any expected/domain failure, throw a **typed** exception so the client gets a clean 4xx, not a 500. Idiomatic path: your exception implements \`Flarum\\Foundation\\KnownError\` (\`getType(): string\` returns a stable type string), you map that type to a status with \`->status('my_type', 429)\`, and you ship a \`<my_type>_message\` locale key for the human text (the client renders the type via that key; the exception **message is never sent**). For a third-party exception you don't control, map it with \`->type(ThirdPartyException::class, 'my_type')\` (plus \`->status\`), or take full control with \`->handler(Exception::class, Handler::class)\` returning a \`HandledError\`. Reuse the built-ins instead of reinventing: \`assertCan\` is 403, \`assertRegistered\` 401, \`findOrFail\`/\`ModelNotFoundException\` 404, \`ValidationException\` 422. Never let an expected error fall through to the \`unknown\`/500 path (it leaks a 500 and spams the reporters).
- **Rate-limit write endpoints** (\`Extend\\ThrottleApi\`), in addition to (never instead of) permission gating: \`->set('myext.create', fn (ServerRequestInterface $request) => …)\` where the callback returns \`true\` to block (becomes a 429 \`too_many_requests\`), \`false\` to **force-allow** (overrides all throttlers, use sparingly), or \`null\` to abstain. Throttlers run on **every** API route, so gate on \`$request->getAttribute('routeName')\` yourself, read the actor via \`RequestUtil::getActor($request)\`, and keep the actual counts in the cache / Laravel \`RateLimiter\` (the extender only decides block vs allow, it doesn't count for you). \`->remove('name')\` drops a throttler. Throttling caps frequency for already-authorized actors; \`assertCan(...)\` stays the security gate.
- **Atomic multi-row creation**: when creating a parent + its first child (ticket+first reply, discussion+first post), do it in one transaction (and take a row lock if a rate/quota check must be TOCTOU-safe) so a failure can't leave an orphan.
- **Models**: add \`@property\`/\`@property-read\` PHPDoc for columns and relationships (PHPStan needs it, and it documents the schema); use \`$casts\` (not the deprecated \`$dates\`); type relationship methods.
- **A custom model, end to end.** The class extends \`Flarum\\Database\\AbstractModel\` (set \`$table\`, use \`$casts\`, \`@property\` docblocks, typed relationship methods; note \`$timestamps = false\` by default, opt in with \`public $timestamps = true\`). Raise domain events with \`EventGeneratorTrait\` (\`$model->raise(...)\`) and dispatch them from your handler via \`DispatchEventsTrait::dispatchEventsFor(...)\`. Use \`Extend\\Model(SomeModel::class)\` only to **add** relations/casts/defaults to an existing model (\`->belongsTo\`/\`hasMany\`/\`belongsToMany\`/\`relationship\`/\`cast\`/\`default\`; there is no \`dateAttribute\` in 2.0, use \`->cast($attr, 'datetime')\`). Make your content permission-aware (the flip side of respecting moderation state): \`use ScopeVisibilityTrait\` on the model, register an invokable scoper with \`(new Extend\\ModelVisibility(MyModel::class))->scope(MyScope::class[, 'ability'])\` plus a policy via \`(new Extend\\Policy())->modelPolicy(MyModel::class, MyPolicy::class)\`, then **always query \`MyModel::whereVisibleTo($actor)\`** (scoping is opt-in per query; a bare query leaks everything). Expose it over the API with \`Extend\\ApiResource\` and on the client with a \`Model\` subclass registered via \`new Extend.Store().add('my-type', MyModel)\`. The JSON:API \`type\` string must be byte-identical across the resource, the store, and every \`app.store\` call, and the table needs a migration; a model with no API resource is unreachable over HTTP.
- **Migrations** portable + idempotent: \`createTableIfNotExists\`/\`addColumns\`; wrap FK drops in try/catch instead of probing \`information_schema\` (which doesn't exist on SQLite/Postgres); chunk backfills; race-safe unique indexes; seed permissions via migration.
- **Write portable queries, the reusable CI runs MySQL, MariaDB, PostgreSQL *and* SQLite.** MySQL is lenient where Postgres is strict, so a query that's green locally on MySQL can 500 only on the Postgres CI job. Concretely: do **not** \`distinct()\` a \`SELECT *\` that pulls a model with a JSON column (e.g. \`users.preferences\`), Postgres has no equality operator for \`json\` and fails with \`SQLSTATE 42883\`; an \`EXISTS\`-style \`whereHas\`/\`orWhereHas\` filter never duplicates rows, so it needs no \`distinct()\` in the first place. Let \`$casts\` bind booleans rather than comparing a boolean column to \`0\`/\`1\` literals; don't rely on implicit row order or MySQL's loose \`GROUP BY\`. When you must diverge per driver, branch on \`$connection->getDriverName()\`.
- **Postgres aborts the entire transaction on the first failed statement** (\`SQLSTATE 25P02\`, "current transaction is aborted"): every later query in that transaction fails until rollback. So a \`try/catch\` around a DB call *inside* a write transaction is a trap, it swallows the real error while the transaction is already poisoned, and the *next* query is the one that 500s, masking the true cause (find the first exception in \`storage/logs/flarum-*.log\`). Keep best-effort or optional work (notification-recipient lookups, audit logging, analytics) **out** of the write transaction, not merely wrapped in try/catch.
- **Request-scoped state, never statics or singletons.** Under a persistent runtime (FrankenPHP/Swoole/Octane/RoadRunner) one process serves many requests and users, so request state left in a \`static\` or an app-scoped singleton bleeds across them (a privilege-leak class of bug, not just staleness). Resolve the actor fresh per request via \`Flarum\\Http\\RequestUtil::getActor($request)\` (never stash the \`User\`); read input from the PSR-7 \`ServerRequestInterface\` (\`getQueryParams\`/\`getParsedBody\`/\`getCookieParams\`/\`getHeaderLine\`), never \`$_GET\`/\`$_POST\`/\`$_COOKIE\`/\`$_SERVER\`; don't depend on \`register_shutdown_function\`/\`exit\`/request-end side effects or on memory being reclaimed (don't accumulate per-request data into a singleton); keep singletons stateless (no cached request/actor/settings snapshot). This is the same discipline a queue or multi-server handler needs. Set \`Secure\` cookies only on HTTPS.
- **Settings**: \`Extend\\Settings\` with \`->default()\` + \`->serializeToForum()\` (camelCase frontend key); keep server-only settings unserialized. Consider a default-true **kill-switch** setting so the behaviour can be neutralised without disabling the extension.
- **Admin settings & permissions UI** (the frontend half of \`Extend\\Settings\`): in 2.0 the object was renamed \`app.extensionData\` to **\`app.registry\`** (\`app.extensionData\` no longer exists). \`app.registry.for('vendor-ext').registerSetting({ setting: 'vendor-ext.key', label, type })\` auto-builds a default settings page (no page component needed); \`type\` is \`'bool'\`/\`'switch'\`, a raw input type (\`'text'\`/\`'color'\`/...), \`'select'\` (with \`options\` + \`default\`), or \`'textarea'\`. \`registerSetting(content, priority, key)\` and \`registerPermission(content, type, priority)\` take **positional** priority/type args; a permission's \`type\` is \`'view'\`/\`'start'\`/\`'reply'\`/\`'moderate'\`. The \`setting:\` key is the literal DB settings key the admin reads/writes (no \`serializeToForum\` needed for an admin-only setting; \`serializeToForum('camelKey', 'vendor-ext.key')\` only exposes a value to the forum payload, which is the camelCase-front / dotted-back split). A registered permission is UI only: enforce it backend-side (\`assertCan\` + a \`Policy\`) and **seed its default in a migration** (\`Migration::addPermissions(...)\`) or no group holds it. Never \`serializeToForum\` a secret. Build a custom page (extend \`ExtensionPage\` + \`app.registry.registerPage(...)\`) only when the auto page isn't enough.
- **Prefer the model store on the frontend** (\`app.store.find\`/\`createRecord().save()\`) over raw requests, so caching and reactivity work.`,
  },
  scaling: {
    title: "Scaling: queues, Redis, files, multi-server",
    body: `Write the extension so it stays correct on a real production stack (background workers, Redis, object storage, multiple app servers), not just a single-box default install.
- **Queue-driver portability.** Stock Flarum defaults to the \`sync\` queue, so a dispatched job runs **inline, in the web request, before \`dispatch()\` returns**; \`database\`/\`redis\` defer it to a separate worker process, possibly minutes later and on another machine. Write every job to be correct under **both**: don't read its result on the next line assuming it hasn't run (under \`sync\` it has), and don't assume it was backgrounded (slow work under \`sync\` blocks the user's request). If work truly must not block, document that admins need a real queue driver, never assume one.
- **Job design.** Dispatch through the bus (inject \`Illuminate\\Contracts\\Bus\\Dispatcher\`, or the \`dispatch()\` helper); extend \`Flarum\\Queue\\AbstractJob\` (it implements \`ShouldQueue\` + \`Queueable\` + \`SerializesModels\`). Keep the payload small and serializable: pass **IDs, not Eloquent models**, and re-fetch in \`handle()\` (a queued model reloads by primary key at run time, so the handler sees current DB state and throws if the row was deleted). Make handlers **idempotent and retry-safe**, delivery is at-least-once, so a job can run twice (use \`ShouldBeUnique\` to dedupe). Use **no request-scoped state** (under a CLI worker there is no session/\`$request\`/actor): capture the actor's id in the constructor and re-resolve in \`handle()\`. Set \`$tries\`/\`$timeout\`/\`backoff()\` and implement \`failed()\`.
- **Cache / Redis (fof/redis).** When fof/redis is installed, cache, session, and queue become Redis-backed and **shared across every web node and worker**. Keep shared or persistent state in the cache abstraction (\`Illuminate\\Contracts\\Cache\\Repository\`), **never** in the filesystem, APCu, or a static/in-process variable (those are per-process and break the moment the forum is multi-node). Treat cache as **non-authoritative**: it can evict, flush, or be unavailable at any time, so always have a recompute-on-miss path and never store the only copy of anything there. **Namespace** your cache keys (you share one keyspace with core and every other extension) and use tags for grouped invalidation instead of flushing the store.
- **Horizon (fof/horizon)** only supervises the \`redis\` queue. To be Horizon-friendly, queue real jobs (never \`dispatchSync\`), add \`displayName()\` and \`tags()\` so they're findable in the dashboard, put heavy work on a **named queue** (\`public static ?string $onQueue\`) so an operator can balance it separately, and keep handlers short with sane \`timeout\`/\`tries\` so a worker isn't pinned.
- **Multi-server file storage.** Never write to local paths (\`storage_path()\`/\`public_path()\`/\`fopen()\`/\`move_uploaded_file()\`) for anything another request or server must read: behind a load balancer, local disk is not shared and \`storage/\` is not guaranteed shared. Declare a disk with \`Extend\\Filesystem->disk('my-ext', ...)\`, write through it (inject \`Illuminate\\Contracts\\Filesystem\\Factory\`, then \`->disk('my-ext')->put($path, $bytes)\`), and let admins repoint it at S3 or shared storage via the \`disk_driver.my-ext\` config/setting key. Build public URLs with \`$disk->url($path)\`, never a hand-made web-root path (on S3 it's a bucket/CDN host). Multi-server-safe state is the DB plus a disk on shared/object storage.
- **Assets vs runtime files.** Ship static JS/CSS via \`Extend\\Frontend()->css()/->js()\` (there is no \`Extend\\Asset\` for bundles); \`flarum assets:publish\` copies them onto the assets disk, so they follow the admin's S3 driver automatically. Files generated at runtime (uploads, exports, generated images) go to a disk **you** declared, never into the published-assets tree. An uploaded file or a \`tmpfile()\` is valid only within the one request on the one server that holds it, so stream it onto a disk before the request ends and never hand a queued job a local temp path. Set disk **visibility** (\`Visibility::PUBLIC\`/\`PRIVATE\`), don't \`chmod\`.
- **Portable URLs (sub-path, multi-domain, reverse proxy, CDN).** Everything derives from the \`url\` in \`config.php\` (Flarum never sniffs the request host), so generate URLs through it, never by hand. Backend: inject \`Flarum\\Http\\UrlGenerator\` and use \`->to('forum'|'api'|'admin')->route('name', $params)\`/\`->path(...)\`/\`->base()\`; register routes with \`Extend\\Routes\`. Frontend: use \`app.route(name, params)\` and \`app.forum.attribute('baseUrl'|'basePath'|'apiUrl'|'assetsBaseUrl')\`, never \`window.location\` or a hardcoded \`/\`. Resolve any static file through the \`flarum-assets\` disk's \`->url()\`: the assets host may be a CDN/S3 on a different origin, so never hardcode \`/assets/...\`. Behind a TLS-terminating proxy, correctness comes from setting \`url\` to the external \`https://...\` value; core has no \`trustedProxies\`/\`X-Forwarded\` handling, so don't read \`$_SERVER\` to infer scheme or host. Emails and any other out-of-request URL must be absolute, built via \`UrlGenerator\`.
- **Console commands & scheduled tasks** (\`Extend\\Console\`): \`->command(MyCommand::class)\` (extend \`Flarum\\Console\\AbstractCommand\` or Illuminate \`Command\`; a Laravel-style \`handle()\` is container-injected) and \`->schedule(MyCommand::class, fn (Event $e) => $e->daily()->onOneServer()->withoutOverlapping(), $args)\`. Multi-server: \`schedule:run\` fires on **every** node whose cron calls it, so a task without \`->onOneServer()\` **double-runs** on a multi-node deploy; \`onOneServer()\`/\`withoutOverlapping()\` need a **shared cache** (Redis or \`database\`), and a task that can't use them must be idempotent. Scheduling only happens if the admin installed the system cron (\`* * * * * php flarum schedule:run\`), so document it, don't assume it. Keep the scheduled command thin and dispatch heavy work as a queued job (see queue-driver portability above). Console runs with no HTTP actor or request, so resolve everything explicitly.`,
  },
  integrations: {
    title: "Optional ecosystem integrations",
    body: `Light up when popular optional extensions are present, without ever hard-depending on them.
- **Soft-dependence pattern (use this for everything below).** List the extension under \`suggest\` (or \`extra.flarum-extension.optional-dependencies\`), **never \`require\`**. Backend: wrap the integration extenders in \`(new Extend\\Conditional())->whenExtensionEnabled('<ext-id>', fn () => [ ... ])\` so its classes are never referenced when it's absent. Frontend: gate with \`'<ext-id>' in flarum.extensions ? [ ... ] : []\` and resolve the other extension's classes at **initializer time** via \`flarum.reg.get('<ext-id>', '<path>')\` (guard for \`undefined\`), never a top-level \`ext:\`/\`import\` (which forces a hard dep and is load-order fragile). Always degrade gracefully: the feature must still work by normal page load when the optional extension, or its server-side daemon/worker, is missing.
- **flarum/tags** (\`flarum-tags\`): present on most forums, so be tag-aware. Read a discussion's tags via the \`tags\` relation (\`$discussion->tags\`, model \`Flarum\\Tags\\Tag\`) only when enabled. **Tag-scoped permissions** are ordinary group-permission rows prefixed \`tag{id}.\`, and only \`is_restricted\` tags gate anything. To make your own ability tag-scopable, register it as a discussion permission (so it appears in the per-tag grid) and check it on the **Discussion** with \`$actor->can('myext.doThing', $discussion)\`: \`DiscussionPolicy\` then applies the per-tag gate automatically. For bulk filtering use \`Tag::whereHasPermission($actor, 'ability')\` (it already encodes restricted-vs-global and parent inheritance), not a manual loop, and never write \`tag{id}.\` rows yourself (tags maintains them). Frontend: \`discussion.tags()\`, gated by \`'flarum-tags' in flarum.extensions\` + \`flarum.reg.get('flarum-tags', ...)\`. Gotchas: a child tag inherits its parent's restriction; a discussion is hidden if the actor lacks the permission in **any** of its restricted tags; and the primary-tag-count settings can block \`startDiscussion\`, so creating a discussion programmatically must attach a valid primary tag (or the actor must hold \`bypassTagCounts\`).
- **flarum/realtime** (\`flarum-realtime\`): integration is mostly **implicit**, fire standard notification Blueprints and standard domain events (post/discussion lifecycle) and realtime pushes them automatically, serialized **per recipient through your API resource**, so correct resource visibility/fields *is* the contract. Only for custom mutations do you wire \`Flarum\\Realtime\\Extend\\Realtime->broadcastModelEvent(...)\` (plus \`registerModelEndpoint()\` for non-core models) and the frontend \`RealtimeExtend\`. It needs a websocket daemon **and** a running queue, so never assume a push arrives: live updates are an enhancement over normal loads, never the transport of record.
- **flarum/audit** (\`flarum-audit\`): not automatic. Make a custom action auditable with \`Flarum\\Audit\\Extend\\Audit->listen(MyEvent::class, 'myext.action', fn ($e) => [...])\`. Store **IDs under conventional keys** (\`discussion_id\`/\`post_id\`/\`user_id\`/\`tag_id\`) so entries render as links, and add the \`flarum-audit.lib.browser.<action>\` locale key or the entry shows a raw JSON dump. Attribution is request-scoped (actor and IP come from the HTTP middleware), so actions in jobs/console log a null actor; the log is append-only, so never put secrets or tokens in the payload.
- **fof/forum-widgets-core** (\`fof-forum-widgets-core\`): frontend-only, no backend extender. In an initializer resolve \`flarum.reg.get('fof-forum-widgets-core', 'common/components/Widget')\` (the base class) and \`'common/extend/Widgets'\` (the extender), guard for \`undefined\`, subclass \`Widget\` (override \`className\`/\`icon\`/\`title\`/\`content\`), then register \`new Widgets().add({ key, component, placement, isUnique })\` where \`placement\` is \`start_top | start_bottom | top | bottom | end\`.
- **fof/sitemap** (\`fof-sitemap\`): register \`(new FoF\\Sitemap\\Extend\\Sitemap())->addResource(MyResource::class)\` (or \`->addStaticUrl('route-name')\` for a fixed page) inside a Conditional. \`MyResource extends FoF\\Sitemap\\Resources\\Resource\` and implements \`query()\` (return only **guest-visible** rows), \`url($model)\`, \`priority()\`, and \`frequency()\`. Cached mode writes to the \`flarum-sitemaps\` disk (default local \`{public}/sitemaps\`, not the DB), so on multiple servers repoint that disk to shared/S3 storage or build on a shared-storage node.
- **Respect moderation state** (flarum/lock, /sticky, /approval, /flags, /subscriptions). One rule covers most of it: **never query moderatable models raw**. Read through \`->whereVisibleTo($actor)\` or the API resource (which fires the registered \`ModelVisibility\` scopes) and act through \`$actor->can($ability, $model)\`, so locks and approval are enforced for you and pending/hidden content never leaks. Specifics: **lock** is \`is_locked\` on Discussion, enforced by the \`reply\` policy (check \`can('reply')\`, don't test the column or bypass it); **approval** is \`is_approved\` (default true) on Post/Discussion, hidden-until-approved by a visibility scope (a raw query leaks pending content; don't filter \`is_approved\` yourself); **sticky** is \`is_sticky\`, pinned by a search mutator (list/sort through \`DiscussionSearcher\`, not \`Discussion::orderBy\`, or you drop the pin); **flags** is the post-scoped \`Flarum\\Flags\\Flag\` model (flagging targets posts, so don't assume a new entity is flaggable); **subscriptions** is the \`subscription\` (\`follow\`/\`ignore\`) state on \`UserState\` (honor \`ignore\` in your own notifications, and use \`->beforeSending\` to drop recipients who can't see the content). React to the named events (\`PostWasApproved\`, \`DiscussionWasLocked\`, ...), not column polls. Soft-depend on each via \`whenExtensionEnabled('flarum-<name>')\`.
- **flarum/likes** (\`flarum-likes\`) and the reaction ecosystem. A like is the \`post_likes\` pivot (\`(new Extend\\Model(Post::class))->belongsToMany('likes', User::class, 'post_likes', 'post_id', 'user_id')\`); the canonical **toggle-a-per-user-relationship over JSON:API** pattern is a \`Schema\\Boolean::make('isLiked')->visible(false)->writable(<can like>)->set(<attach/detach + raise event>)\` field (reuse this shape for any per-user toggle). To award points, notify, or react, listen to \`Flarum\\Likes\\Event\\PostWasLiked\`/\`PostWasUnliked\` (each \`(Post $post, User $user)\`) via \`Extend\\Event\`, guarding against self-likes. Broader: **fof/reactions** (\`fof-reactions\`) fires \`FoF\\Reactions\\Event\\PostWasReacted\` carrying the \`Reaction\` type, and **fof/gamification** (\`fof-gamification\`) replaces likes with votes and fires \`UserPointsUpdated\`. Soft-depend on each.
- **Accepting file uploads** (fof/upload, or the core avatar pattern). Never roll your own raw upload handling: take a PSR-7 \`UploadedFileInterface\` from \`$request->getUploadedFiles()\` (not \`$_FILES\`), validate size and the **sniffed** mime (don't trust the client's extension; sanitize SVGs) with an \`AbstractValidator\` so a bad file is a \`ValidationException\` not a 500, and store through a declared \`Extend\\Filesystem\` disk (\`$factory->disk('my-ext')->put(...)\`/\`->url()\`) so it works multi-server (see file storage under \`scaling\`). Reuse **fof/upload** (\`fof-upload\`: its \`UploadAdapter\` system, admin UI, per-mime permissions, \`File\` model and \`WillBeUploaded\`/\`WasSaved\` events) for a shared media library; write a focused avatar-style uploader (mirror core's \`AvatarUploader\`: own disk, random basename, delete-old-after-save) for a single dedicated artifact. Image processing uses \`intervention/image\`, which **needs \`ext-gd\`** (or imagick), so declare or guard it or a box without GD 500s. Soft-depend on fof/upload; don't hard-require it.
- **flarum/mentions** (\`flarum-mentions\`): your content participating in existing @user/#post mentions is automatic through standard post formatting. **Adding a NEW mentionable entity type is advanced and not a stable API**: mentions' backend is hardcoded per type (a \`@TODO\` to make it a registry is still open), so you add your own s9e tag + runtime resolver via \`Extend\\Formatter\` (mirror \`ConfigureMentions\`), while the frontend autocomplete does have a real extender (\`Mentionables\`: \`.mentionable('@', MyModel)\` on the existing \`@\` format, your model implementing \`type\`/\`search\`/\`replacement\`/\`suggestion\`). Treat it as a moving target; soft-depend (\`whenExtensionEnabled('flarum-mentions')\` / \`'flarum-mentions' in flarum.extensions\`).`,
  },
  i18n: {
    title: "Internationalization",
    body: `- **Every user-facing string is a translation key** across all four layers: frontend (\`app.translator.trans\`/JSX \`tx\`), API exceptions, validation/rate-limit messages, and email blade templates. Inject \`TranslatorInterface\` where needed.
- Namespace keys under \`<vendor>-<ext>.{forum,admin,api}\`; use placeholders (\`{name}\`, \`{count}\`). Ship \`locale/en.yml\` only, other languages are community-contributed.
- **Gotchas**: no angle brackets (\`<tag>\`) in en.yml values (breaks the translator → raw key / blank page); \`user\` is a reserved translator param (use \`{name}\` or a User model + \`{username}\`); keep server-only validation keys out of the frontend bundle.`,
  },
  testing: {
    title: "Testing",
    body: `- Use \`flarum/testing: ^2.0\` (PHPUnit 12). Layout: \`tests/{unit,integration,fixtures}\`, \`tests/integration/setup.php\`, and \`phpunit.unit.xml\` (\`processIsolation="false"\`) + \`phpunit.integration.xml\` (\`processIsolation="true"\`). Keep \`backupGlobals\`/\`backupStaticProperties\` as the docs show. Use PHP 8 attributes (\`#[Test]\`), not docblock annotations.
- **Integration tests are the highest-value coverage**: hit your API endpoints through the middleware stack as different actors (guest / member / staff / admin) to lock in permissions, visibility scoping, create/update/delete, and error codes. They are the automated form of "I tested it on the forum".
- In \`TestCase\`, do all setup (\`extension()\`, \`extend()\`, \`prepareDatabase()\`, \`setting()\`) **before** the app boots (the first \`app()\`/\`send()\`/\`database()\` call boots it; later setup is silently ignored).
- Seed rows in \`prepareDatabase()\` keyed by model class (the harness uses factories), and get ready-made actors from the \`RetrievesAuthorizedUsers\` trait (\`normalUser()\`, admin id 1) so a permissions test is a few lines. Use \`ConsoleTestCase\` for \`Extend\\Console\` commands.
- **Unit tests** for pure logic (validators, permission helpers) via Mockery, mock only the few interactions under test. Needing lots of mocks is a smell to extract smaller functions.
- Frontend logic: Jest via \`@flarum/jest-config\` where it earns its keep.
- **Testing-environment notes**: the test harness defaults to SQLite; point it at MySQL/MariaDB with \`DB_DRIVER\`/\`DB_*\` env vars + \`composer test:setup\` if that matches production. An unauthenticated POST is rejected by Flarum's CSRF guard (HTTP 400) before the auth gate (401), for "a guest can't write" assert rejection + that nothing was persisted, not a specific status code.
- **The reusable backend CI runs the full database matrix** (MySQL 5.7/8.0, MariaDB, PostgreSQL, SQLite, each with and without a table prefix) across several PHP versions. Passing locally on one database is **not** the same as green: the classic failure is code that works on MySQL but 500s only on Postgres (see Backend → portable queries). If you can't run Postgres/SQLite locally, treat CI as the portability gate; to reproduce a Postgres-only failure, run the suite against a throwaway Postgres container with \`DB_DRIVER=pgsql\` and read the first exception from \`storage/logs/flarum-*.log\`.`,
  },
  "quality-ci": {
    title: "Static analysis, formatting & CI",
    body: `- **PHPStan**: \`flarum/phpstan: ^2.0\`; \`phpstan.neon\` includes \`vendor/flarum/phpstan/extension.neon\`, \`level: 6\`, paths \`extend.php\`+\`src\`, exclude \`*.blade.php\`, \`databaseMigrationsPath: ['migrations']\`. It boots the app for symbol resolution (so it needs the test DB env) and benefits from \`--memory-limit=1G\`.
  - First-run recipe to reach zero: add \`@property\` docblocks to models; declare extended attributes with \`Extend\\Model(...)->cast(...)\`; you cannot narrow an \`object $model\` lifecycle-hook parameter in the signature (PHP contravariance), so add an inline \`/** @var <Model> $model */\` at the top of the body; in a \`scope(Builder $query)\` add \`/** @var \\Illuminate\\Database\\Eloquent\\Builder<<Model>> $query */\` so soft-delete builder methods (\`withTrashed()\`) resolve; type \`$dates\` and notification-blueprint params.
- **Formatting**: Prettier via the shared \`@flarum/prettier-config\` (\`"prettier": "@flarum/prettier-config"\` in package.json) + \`format\`/\`format-check\` scripts. (PHP style is left to PHPStan; no PHP-CS-Fixer.)
- **CI**: reuse the framework workflows instead of hand-rolling. \`.github/workflows/backend.yml\` → \`flarum/framework/.github/workflows/REUSABLE_backend.yml@2.x\` (\`enable_backend_testing: true\`, \`enable_phpstan: true\`). \`.github/workflows/frontend.yml\` → \`REUSABLE_frontend.yml@2.x\` (\`enable_prettier: true\`, \`enable_typescript\` if you ship the typings scripts, \`enable_bundlewatch: false\`, \`js_package_manager\`, \`main_git_branch\`). The frontend workflow builds/commits \`dist\` so it never goes stale.
- Add an \`.editorconfig\` (lf, utf-8, 4-space; 2-space for md/yml).`,
  },
  release: {
    title: "Releasing",
    body: `- A README with a clear description and a LICENSE (MIT or similar for a public extension; \`proprietary\` for a private/site-specific one). Tag releases with SemVer (\`git tag vX.Y.Z\` && \`git push --tags\`); submit once to Packagist, then enable auto-update so future releases are just commit/tag/push.
- **The tag is the release**, Packagist publishes from the git tag, so a commit merely *titled* "Release vX.Y.Z" with no actual tag ships nothing. Cut (and push) the real tag, and a GitHub Release if you announce there. A version bump isn't done until the tag exists on the remote.
- **Write release notes for the people who install the extension** (forum admins), not for developers: describe what the user experiences, in plain language. The release/tag body can serve as the changelog.
- Commit messages: imperative subject; body that explains the root cause, the fix, and how you verified it. Keep them honest about what was and wasn't tested.`,
  },
  porting: {
    title: "Porting a 1.x extension to 2.0",
    body: `A checklist of the breaking changes, biggest first. Port against a real 2.0 extension (flarum/tags, flarum/likes) as a reference, and prefer scaffolding a fresh \`flarum-cli init\` 2.0 skeleton and moving your logic into it over mutating the 1.x tree.
- **composer.json**: \`flarum/core: ^1.0\` becomes \`^2.0\`; \`php: ^7.4\` becomes **\`^8.3\`**; set other \`flarum/*\` deps to \`"*"\`; add \`"minimum-stability": "beta"\` while 2.0 is pre-stable. Transitive bumps you may feel: Laravel 8 to 13, Symfony 5 to 7, Carbon 2 to 3, Flysystem 1 to 3.
- **Serializers are gone (the biggest change).** Delete every \`AbstractSerializer\` and the \`Extend\\ApiSerializer\` extender. A resource is now a \`Flarum\\Api\\Resource\\AbstractDatabaseResource\` with \`type()\`/\`model()\`/\`fields()\`, registered with \`Extend\\ApiResource\`; to add fields to core's resources use \`(new Extend\\ApiResource(DiscussionResource::class))->fields(MyFields::class)\` returning \`Schema\\*\` objects (\`Schema\\Boolean\`/\`Str\`/\`Integer\`/\`Relationship\\ToOne\`/\`ToMany\`, built \`::make('name')->get()/->writable()/->set()/->visible()\`). See "Adding a field to an existing resource" under Backend.
- **Controllers are gone too.** Delete \`Extend\\ApiController\` and the \`AbstractCreate/Show/List/Update/DeleteController\` classes; customize endpoints with \`->endpoint(Endpoint\\Index::class, fn ($e) => …)\` (\`Flarum\\Api\\Endpoint\\*\`) and read the actor/request via \`Flarum\\Api\\Context\` (\`$context->getActor()\`).
- **Search/filtering rewritten.** Delete \`Extend\\Filter\`, \`AbstractFilterer\`, and all **backend gambits** (gambits are frontend-only now). Register filters via \`Extend\\SearchDriver(DatabaseSearchDriver::class)->addFilter(SomeSearcher::class, MyFilter::class)\` implementing \`Flarum\\Search\\Filter\\FilterInterface\`. Namespaces moved \`Flarum\\Query\\*\` to \`Flarum\\Search\\*\`, and DB search now hands you an **Eloquent** builder, not a query builder.
- **Models**: \`protected $dates\` and \`Extend\\Model->dateAttribute()\` are gone; use \`$casts = ['x' => 'datetime']\` or \`->cast('x', 'datetime')\`. Relation methods keep their names but now want explicit generic return types (\`@return HasMany<Model, $this>\`).
- **Notifications**: \`Extend\\Notification->type(Blueprint, Serializer, [...])\` (3-arg) becomes \`->type(Blueprint, ['alert', 'email'])\` (2-arg; the serializer arg is gone), and the Blueprint must implement \`AlertableInterface\` for the alert channel. Email \`getEmailView()\` becomes \`getEmailViews()\` returning \`['text' => …, 'html' => …]\` (split blades into \`views/emails/{html,plain}/\`).
- **Frontend imports**: cross-extension imports need the \`ext:\` prefix (\`import X from 'ext:flarum/tags/...'\`); stop importing from \`@flarum/core\`; the compat layer is gone.
- **Frontend admin**: \`app.extensionData\` is now **\`app.registry\`** (or the declarative \`Admin\` extender). Common component moves: the \`avatar()\`/\`icon()\` helpers became \`Avatar\`/\`Icon\` components; \`Modal\` split into \`Modal\` + \`FormModal\`; \`IndexPage.prototype.sidebar\` moved to a new \`IndexSidebar\` component.
- **Locale HTML**: literal tags like \`<a href='{link}'>\` in en.yml become custom vnode tags (\`<link>...</link>\`) with the vnode passed as a parameter (the no-raw-angle-bracket rule).
- **Tooling & testing**: \`flarum-webpack-config ^2\` to \`^3\`, \`flarum-tsconfig ^1\` to \`^2\`; PHPUnit 9 to 12 with **PHP 8 attributes** (\`#[Test]\`) instead of docblock annotations; \`flarum/phpstan ^2\` at level 6 (generic rename \`TModelClass\` to \`TModel\`); point reusable CI workflows at the framework's \`@2.x\` branch.`,
  },
};

const TOPIC_KEYS = Object.keys(SECTIONS) as [string, ...string[]];

function render(topic?: string): string {
  if (topic && topic !== "all") {
    const s = SECTIONS[topic];
    if (s) return `# ${TITLE}\n\n## ${s.title}\n\n${s.body}\n`;
  }
  const all = Object.values(SECTIONS)
    .map((s) => `## ${s.title}\n\n${s.body}`)
    .join("\n\n");
  return `# ${TITLE}\n\n${INTRO}\n\n${all}\n`;
}

/** Register the static extension-development reference tool. Needs no forum/API key. */
export function registerDevTools(server: McpServer): void {
  server.registerTool(
    "flarum_dev",
    {
      title: "Flarum extension development reference",
      description:
        "A development reference for building or reviewing a Flarum 2.0 extension: scaffolding and " +
        "architecture, composer.json, the TypeScript frontend, backend (API resources/models/migrations), " +
        "scaling (queue-driver portability, Redis, multi-server file storage), optional ecosystem " +
        "integrations (realtime, audit, fof widgets, fof sitemap), i18n, testing, static analysis & CI, " +
        "releasing, and porting a 1.x extension to 2.0. Combines the conventions the official docs establish, the de-facto FriendsOfFlarum " +
        "standard, and patterns that prevent real production bugs " +
        "(fail-closed API fields, lazy-chunk-safe extends, atomic creation, the PHPStan/testing setup). " +
        "Consult it before scaffolding, when adding a feature, or when reviewing extension code. " +
        "Pair with flarum_docs_search/flarum_docs_get for the authoritative API reference. " +
        "Omit `topic` for the full reference, or pass one to narrow it.",
      inputSchema: {
        topic: z
          .enum([...TOPIC_KEYS, "all"])
          .optional()
          .describe(
            "Section to return: scaffold, composer, frontend, backend, scaling, " +
              "integrations, i18n, testing, quality-ci, release, porting (or 'all' / " +
              "omit for the full reference).",
          ),
      },
    },
    async ({ topic }) => ({
      content: [{ type: "text" as const, text: render(topic) }],
    }),
  );
}
